---
- name: create build env
  hosts: build
  become: yes

  tasks:

  - name: Ensure pkgs is present
    apt:
      name:
       - docker.io
       - python3-pip
      update_cache: yes

  - name: pip docker-compose
    pip:
      name: docker-compose

  - name: git checkout repo from hw 7
    git:
      repo: 'https://github.com/Evg33/test07.git'
      dest: hw07

  - name: Tear down existing services
    docker_compose:
      project_src: hw07
      state: absent

  - name: Create and start services
    docker_compose:
      project_src: hw07
    register: output

#  - debug:
#      var: output

  - name: Run `docker-compose up` again
    docker_compose:
      project_src: hw07
      build: yes
    register: output

#  - debug:
#      var: output

  - assert:
      that: "not output.changed "

  - name: Stop all services
    docker_compose:
      project_src: hw07
      build: no
      stopped: yes
    register: output

#  - debug:
#      var: output

  - assert:
      that:
        - "not web.hw07_web_1.state.running"

#  - name: Log into DockerHub
#    docker_login:
#      username: ***
#      password: ***
#      email: ***

  - name: Tag and push to docker hub
    docker_image:
      name: evg33/tes07web
      repository: evg33/hw08web:0.0.1
      push: yes
      source: local

- name: create prod env
  hosts: prod
  become: yes

  tasks:

  - name: Ensure pkgs is present
    apt:
      name:
       - docker.io
       - python3-pip
      update_cache: yes

  - name: pip docker-compose
    pip:
      name: docker

  - name: remove container
    docker_container:
      name: web
      state: absent

  - name: Start a container with a command
    docker_container:
      name: web
      image: evg33/hw08web:0.0.1
      state: started
      ports:
       - "80:8080"

  - name: Get my public IP
    ipify_facts:
    register: public_ip

  - name: Show IP
    debug: msg="{{ public_ip }}"
