#!/usr/bin/env ansible-playbook
---
- name: create build env
  hosts: build
  become: yes

  vars_files:
    - secrets.yml

  tasks:

  - name: Ensure pkgs is present
    apt:
      name: [docker.io, python3-pip]
      update_cache: yes
      cache_valid_time: 3600

  - name: pip docker-compose
    pip:
      name: docker-compose

  - name: git checkout repo from hw 7
    git:
      repo: 'https://github.com/Evg33/test07.git'
      dest: hw07

  - name: Tear down existing services
    docker_compose:
      project_src: hw07
      state: absent

  - debug:
      var: output

  - name: Remove old war file
    file:
      path: hw07/web/src/hello-1.0.war
      state: absent

  - name: Build war file
    docker_compose:
      project_src: hw07
      build: yes
      services: bldr
    register: output

  - debug:
      var: output

  - name: Wait until the war file is present before continuing
    wait_for:
      path: hw07/web/src/hello-1.0.war

  - name: Build web service
    docker_compose:
      project_src: hw07
      build: yes
      services: web
      stopped: yes
    register: output

  - debug:
      var: output

  - name: Stop all services
    docker_compose:
      project_src: hw07
      build: no
      stopped: yes
    register: output

#  - name: DockerHub Login
#    docker_login:
#      username: "{{ dhlogin }}"
#      password: "{{ dhpass }}"
#      email: "{{ dhemail }}"

  - name: Tag and push to docker hub
    docker_image:
      name: evg33/hw07web:0.0.8
      repository: evg33/hw08web:0.0.4
      push: yes
      source: local

- name: create prod env
  hosts: prod
  become: yes

  tasks:

  - name: Ensure pkgs is present
    apt:
      name: [docker.io, python3-pip]
      update_cache: yes
      cache_valid_time: 3600

  - name: pip docker-compose
    pip:
      name: docker

  - name: Start container
    docker_container:
      name: web
      image: evg33/hw08web:0.0.4
      state: started
      ports:
       - "80:8080"
      auto_remove: yes
      pull: yes
      recreate: yes

  - name: Get my public IP
    ipify_facts:
    register: public_ip

  - name: Show url
    debug: msg="    http://{{ hostvars[inventory_hostname]['ipify_public_ip'] }}/hello-1.0    "
